### ISSUE TITLE
development.py in module Test missing

### ISSUE THREAD

**Issue by butterjust** [Brilight/DeePEB#2]
In Test.Evaluate, there is `from development import development as Dev`, but i can't find development.py in folder Test or any other folder

**Comment by Brilight** [comment]
Well, this is an Eikonal solver developed by our group member, which is not published or opened. So you can replace it with other Eikonal Solvers, simulating the etching/developing process given the development rate input and outputs the final arrival time.

**Comment by butterjust** [comment]
> Well, this is an Eikonal solver developed by our group member, which is not published or opened. So you can replace it with other Eikonal Solvers, simulating the etching/developing process given the development rate input and outputs the final arrival time.

OK,thank you
